exp_name: MLP_AS_aria-brp
model_name: SimpleMLP
graph_name: mlp
dataset: egoexo-aria-brp # name of the directory in features/ where the features are stored
loss_name: ce #_ref
use_spf: false
use_ref: false
w_ref: 5
num_modality: 1
# channel1: 1024
# channel2: 512
final_dim: 170 # number of output classes
input_dim: 756
# num_att_heads: 4
dropout: 0.2
lr: 0.0001
wd: 0
batch_size: 5000
sch_param: 5
num_epoch: 50
sample_rate: 1
crop: false