exp_name: MLP_AS_aria-lr_0.0005
model_name: SimpleMLP
graph_name: mlp
dataset: egoexo-omnivore-aria
loss_name: ce #_ref
use_spf: false
use_ref: false
w_ref: 5
num_modality: 1
# channel1: 1024
# channel2: 512
final_dim: 497
input_dim: 1536
# num_att_heads: 4
dropout: 0.2
lr: 0.0001
wd: 0
batch_size: 5000
sch_param: 5
num_epoch: 45
sample_rate: 1
crop: false
