exp_name: gravit-aria-base #MLP_AS_aria-lr_0.0005
model_name: SPELL # SimpleMLP 
graph_name: egoexo-omnivore-aria_10_10 # name of saved dir in data/graphs
dataset: egoexo-omnivore-aria
loss_name: ce_ref
use_spf: False
use_ref: true
w_ref: 1
num_modality: 1
channel1: 1300
channel2: 600
final_dim: 497  # Number of classes
input_dim: 1536  # Input dimension of features
num_att_heads: 0
dropout: 0.2
lr: 0.0005
wd: 0
batch_size: 1
sch_param: 5
num_epoch: 45
sample_rate: 1
crop: False
