exp_name: gravit-aria-segmentwise # gravit-aria-base #MLP_AS_aria-lr_0.0005
model_name: SPELL # SimpleMLP 
graph_name: egoexo-omnivore-segmentwise_10_10 # name of saved dir in data/graphs
dataset: egoexo-omnivore-segmentwise
loss_name: ce #_ref
use_spf: False
use_ref: False
w_ref: 5
num_modality: 1
channel1: 1024
channel2: 512
final_dim: 497  # Number of classes
input_dim: 1536  # Input dimension of features
num_att_heads: 4
dropout: 0.2
lr: 0.0001
wd: 0
batch_size: 1
sch_param: 5
num_epoch: 45
sample_rate: 1
crop: False
eval_type: AS
label_loading_strategy: regular
