exp_name: gravit-segmentwise-multiview-heterogeneous 
model_name: SPELL_HETEROGENEOUS # SimpleMLP
graph_name: segmentwise-hetero-multiview   # name of saved dir in data/graphs
# graph_name: segmentwise-hetero-ego
graph_name_eval: segmentwise-hetero-ego # when the training data is multiview, the eval data has to be single view
features_dataset: omnivore-segmentwise-ego
annotations_dataset: egoexo-segmentwise
# text_dataset: detic-object-list-anchors_hands_sorted_features
spatial_dataset: depthmap #composite_40 #features_5objects


load_segmentwise: True
loss_name: ce #_ref
use_spf: False
use_ref: False
w_ref: 1
num_modality: 1
channel1: 1536
channel2: 1024
spatial_input_dim: 3136
final_dim: 495  # Number of classes
input_dim: 1536  # Input dimension of features
num_att_heads: 4
dropout: 0.5
lr: 0.00005
wd: 0.0001
batch_size: 1
sch_param: 45
num_epoch: 50
sample_rate: 1
eval_type: KR
similarity_metric: None #cosine
similarity_threshold: 0.97
tauf: 1
skip_factor: 1000
# 