exp_name: gravit-aria-segmentwise #_t1_sf1000_innerprod # gravit-aria-base #MLP_AS_aria-lr_0.0005
model_name: SPELL # SimpleMLP 
graph_name: egoexo-omnivore-segmentwise #_1_1000_innerprod # name of saved dir in data/graphs
features_dataset: egoexo-omnivore-segmentwise
annotations_dataset: egoexo-omnivore-segmentwise
loss_name: ce #_ref
use_spf: False
use_ref: false
w_ref: 1
num_modality: 1
channel1: 1024
channel2: 512
final_dim: 497  # Number of classes
input_dim: 1536  # Input dimension of features
num_att_heads: 4
dropout: 0.2
lr: 0.0001
wd: 0
batch_size: 1
sch_param: 5
num_epoch: 45
sample_rate: 1
crop: False
eval_type: KR
label_loading_strategy: regular

similarity_metric: None #cosine
similarity_threshold: 0.97
tauf: 1
skip_factor: 1000