exp_name: gravit-segmentwise-multiview-heterogeneous
model_name: SPELL_HETEROGENEOUS # SimpleMLP
# graph_name: multiview-narration   # name of saved dir in data/graphs
graph_name: ego-narration-test
graph_name_eval: ego-narration # when the training data is multiview, the eval data has to be single view
features_dataset: omnivore-segmentwise-ego
annotations_dataset: egoexo-segmentwise-all-categories-test
text_dataset: videorecap-segment-test_features #detic-object-list-all_features #detic-object-list-anchors_hands_sorted_features
# spatial_dataset: clip-videorecap-feats #depthmap #composite_40 #features_5objects


load_segmentwise: True
loss_name: ce #_ref
use_spf: False
use_ref: False
w_ref: 1
num_modality: 1
channel1: 1536
channel2: 1024
spatial_input_dim: 1024
text_input_dim: 1024
final_dim: 287  # Number of classes
input_dim: 1536  # Input dimension of features
num_att_heads: 4
dropout: 0.5
lr: 0.0005
wd: 0.01
batch_size: 32
sch_param: 45
num_epoch: 60
sample_rate: 1
eval_type: KR
similarity_metric: None #cosine
similarity_threshold: 0.97
tauf: 1
skip_factor: 1000
# 