exp_name: gravit-egoexo-subgraph-mamba # gravit-aria-base #MLP_AS_aria-lr_0.0005
model_name: SPELL # SimpleMLP 
graph_name: egoexo-omnivore-subgraphs-multiview # name of saved dir in data/graphs
graph_name_eval: egoexo-omnivore-subgraphs
features_dataset: egoexo-omnivore-ego
annotations_dataset: egoexo-omnivore-aria
is_multiview: True
load_segmentwise: False
loss_name: ce #_ref
use_spf: False
use_ref: false
w_ref: 1
num_modality: 1
channel1: 1536
channel2: 1024
final_dim: 497  # Number of classes
input_dim: 3072 #1536  # Input dimension of features
num_att_heads: 4
dropout: 0.5
lr: 0.00001
wd: 0.0001
batch_size: 1
sch_param: 45
num_epoch: 150
sample_rate: 1
crop: False
eval_type: KR
label_loading_strategy: regular
split: 2
similarity_metric: None #cosine
similarity_threshold: 0.97
tauf: 1
skip_factor: 1000
